config/routes.rb
Rails.application.routes.draw do
  resources :foorms do
    member { get :submissions }
  end
  resources :form_items, only: :new
  resources :form_item_options, only: :new
  resources :submissions, only: [ :new, :create ] do
    collection { get :success }
  end

  get "submit/:uuid", to: "submissions#new", as: "submit_form"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "foorms#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :submission
  belongs_to :form_item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/foorm.rb
class Foorm < ApplicationRecord
  has_many :form_items, dependent: :destroy
  accepts_nested_attributes_for :form_items, allow_destroy: true

  has_many :submissions, dependent: :destroy

  validates :title, presence: true
  validates :uuid, uniqueness: true

  before_create :set_uuid

  private
  def set_uuid
    self.uuid = SecureRandom.base36(12)
  end
end

app/models/form_item.rb
class FormItem < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :form_item_options, dependent: :destroy
  accepts_nested_attributes_for :form_item_options, allow_destroy: true

  belongs_to :foorm

  validates :label, presence: true
  validates :item_type, presence: true

  enum :item_type, {
    text: "text",
    numeric: "numeric",
    dropdown: "dropdown"
  }
end

app/models/form_item_option.rb
class FormItemOption < ApplicationRecord
  belongs_to :form_item

  validates :label, presence: true
  validates :value, presence: true
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :foorm
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers

  scope :for_form, ->(form_id) { includes(answers: :form_item).where(foorm_id: form_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/foorms_controller.rb
class FoormsController < ApplicationController
  before_action :set_foorm, only: %i[ show edit update destroy submissions ]

  # GET /foorms or /foorms.json
  def index
    @foorms = Foorm.all
  end
  # GET /foorms/new

  def new
    @foorm = Foorm.new
  end

  # GET /foorms/1/edit
  def edit
  end

  # POST /foorms or /foorms.json
  def create
    @foorm = Foorm.new(foorm_params)

    respond_to do |format|
      if @foorm.save
        format.html { redirect_to edit_foorm_path(@foorm), notice: "Foorm was successfully created." }
        format.json { render :show, status: :created, location: @foorm }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foorm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foorms/1 or /foorms/1.json
  def update
    respond_to do |format|
      if @foorm.update(foorm_params)
        format.html { redirect_to edit_foorm_path(@foorm), notice: "Foorm was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @foorm }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foorm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foorms/1 or /foorms/1.json
  def destroy
    @foorm.destroy!

    respond_to do |format|
      format.html { redirect_to foorms_path, notice: "Foorm was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  def submissions
    @submissions = Submission.for_form(@foorm.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foorm
      @foorm = Foorm.includes(form_items: :form_item_options).find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def foorm_params
      params.expect(foorm: [ :title, form_items_attributes: [ [ :id, :label, :item_type, :_destroy, form_item_options_attributes: [ [ :id, :label, :value, :_destroy ] ] ] ] ])
    end
end

app/controllers/form_item_options_controller.rb
class FormItemOptionsController < ApplicationController
  def new
    @form_item_option = FormItemOption.new
    @form_item_id = params.expect(:form_item_id)
  end
end

app/controllers/form_items_controller.rb
class FormItemsController < ApplicationController
  def new
    @form_item = FormItem.new
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new
    @foorm = Foorm.includes(form_items: [ :form_item_options ]).find_by(uuid: params.expect(:uuid))
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)
    @submission.save!

    respond_to do |format|
      format.html { redirect_to success_submissions_path, notice: "Your form has been submitted" }
    end
  end

  def success
  end

  private

  def submission_params
    params.expect(submission: [ :submitter, :foorm_id, answers_attributes: [ [ :form_item_id, :value ] ] ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def input_classes
    "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full"
  end

  def blue_btn_classes
    "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer"
  end

  def gray_btn_classes
    "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium"
  end

  def error_class(item, field)
    {
      "focus:outline-blue-600": item.errors[field].none?,
      "border-red-400 focus:outline-red-600": item.errors[field].any?
    }
  end
end

app/helpers/submit_helper.rb
module SubmitHelper
  def form_item_field(form_item, form_builder)
    case form_item.item_type
    when "text"
      form_builder.text_field :value,
        placeholder: "Your Answer",
        class: input_classes,
          id: "submission_answers_attributes__item_#{form_item.id}"
    when "numeric"
      form_builder.number_field :value,
        placeholder: "Your Answer",
        class: input_classes,
        id: "submission_answers_attributes__item_#{form_item.id}"
    when "dropdown"
      form_builder.select :value,
        options_for_select(
          form_item.form_item_options.map { |i| [ i.label, i.value ] }
        ),
        { include_blank: "Please select" },
        { class: input_classes, id: "submission_answers_attributes__item_#{form_item.id}" }
    end
  end
end

app/views/foorms/_foorm.html.erb
<div id="<%= dom_id foorm %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Title:</strong>
    <%= foorm.title %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Uuid:</strong>
    <%= foorm.uuid %>
  </div>
</div>

app/views/foorms/_form.html.erb
<%= form_with(model: foorm, class: "contents") do |form| %>
  <% if foorm.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(foorm.errors.count, "error") %> prohibited this foorm from being saved:</h2>

      <ul class="list-disc ml-6">
        <% foorm.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": foorm.errors[:title].none?, "border-red-400 focus:outline-red-600": foorm.errors[:title].any?}] %>
  </div>

  
  <div id="form_items">
    <% if foorm.form_items.any? %> 
      <%= render foorm.form_items %>
    <% else %>
     <%= render FormItem.new %>
    <% end %>
  </div>

  <%= link_to "Add new question", 
    new_form_item_path, 
    class: [blue_btn_classes, "mb-4"],
    data: { turbo_stream: true }
  %>
  <br />

  <div class="inline">
    <%= form.submit class: blue_btn_classes %>
  </div>
<% end %>

app/views/foorms/edit.html.erb
<% content_for :title, "Editing foorm" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing foorm</h1>
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= render "form", foorm: @foorm %>

  <%= link_to "Show this foorm submissions", submissions_foorm_path(@foorm), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Submit form", submit_form_path(uuid: @foorm.uuid), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to foorms", foorms_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/foorms/index.html.erb
<% content_for :title, "Foorms" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Foorms</h1>
    <%= link_to "New foorm", new_foorm_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="foorms" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @foorms.any? %>
      <% @foorms.each do |foorm| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render foorm %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show submissions", submissions_foorm_path(foorm), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Submit form", submit_form_path(uuid: foorm.uuid), class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_foorm_path(foorm), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", foorm, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No foorms found.</p>
    <% end %>
  </div>
</div>

app/views/foorms/new.html.erb
<% content_for :title, "New foorm" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New foorm</h1>

  <%= render "form", foorm: @foorm %>

  <%= link_to "Back to foorms", foorms_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/foorms/show.html.erb
<% content_for :title, "Showing foorm" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing foorm</h1>

  <%= render @foorm %>

  <%= link_to "Edit this foorm", edit_foorm_path(@foorm), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to foorms", foorms_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this foorm", @foorm, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>

app/views/foorms/submissions.html.erb
<% content_for :title, "Foorms Submissions" %>
<div class="w-full">
  <%= link_to "Back to foorms", foorms_path, class: gray_btn_classes %>

  <div class="grid md:grid-cols-3 gap-2 sm:grid-cols-1 w-full mx-auto">
    <% if @submissions.any? %>
      <% @submissions.each do |submission| %>
      <div class="border-2 my-4 p-4">
          <p>Name: <strong><%= submission.submitter %></strong></p>
          <% if submission.answers.any? %>
            <% submission.answers.each do |answer| %>
              <div class="bg-gray-100 my-5 p-4 rounded-sm">
                <strong><%= answer.form_item.label %></strong><br /><%= answer.value %><br />
              </div>
            <% end %>
          <% else %>
            <p>No answers provided</p>
          <% end %>
          </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No foorms submissions found.</p>
    <% end %>
  </div>
</div>

app/views/form_item_options/_form_item_option.html.erb
<div class="remove-div bg-gray-100 my-5 p-4 border-1" data-controller="removal">
  <p>Option</p>
  <%= fields_for "foorm[form_items_attributes][#{form_item_id}][form_item_options_attributes][#{form_item_option.id || Time.now.to_i}]", form_item_option do |f| %>
    <%= f.hidden_field :id %>
    
    <div class="flex flex-row gap-2">
      <%= f.text_field :label, 
        placeholder: "Label", 
        class: [
          "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", 
          error_class(form_item_option, :label)
        ]
      %>

      <%= f.text_field :value, 
        placeholder: "Value", 
        class: [
          "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", 
          error_class(form_item_option, :value)
        ]
      %>
      <%= f.hidden_field :_destroy, value: 0, data: { "removal-target" => "field" } %>

      <span
        class="sm:w-auto rounded-sm self-end p-2.5 bg-red-500 hover:bg-red-700 text-white cursor-pointer"
        data-action="click->removal#remove">
          Remove
      </span>
    </div>

    <div data-fields-target="formItemOptions" class="hidden">
      <p>Options for select</p>
    </div>
  <% end %>
</div>

app/views/form_item_options/new.turbo_stream.erb
<%= turbo_stream.append "form_item_options_#{@form_item_id}" do %>
  <%= render @form_item_option, form_item_id: @form_item_id %>
<% end %>

app/views/form_items/_form_item.html.erb
<div class="remove-div bg-gray-100 my-5 p-4">
  <p>Question</p>
  <%= fields_for "foorm[form_items_attributes][#{(current_id = (form_item.id || Time.now.to_i))}]", form_item do |f| %>
    <%= f.hidden_field :id %>
    <div data-controller="fields removal">
      <div class="flex flex-row gap-2 content-bottom mb-4">
        <%= f.text_field :label, 
          placeholder: "Label", 
          class: [
            "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
            error_class(form_item, :label)
          ]
        %>
        <%= f.hidden_field :_destroy, value: 0, data: { "removal-target" => "field" } %>

        <%= f.select :item_type,
                      options_for_select(FormItem.item_types, selected: form_item.item_type,),
                      {},
                      { 
                        class:  "block shadow-sm rounded-md border px-3 py-2 mt-2 w-full",
                        data: { "fields-target" => "select", action: "change->fields#check" }
                      }
        %>

        <span
          class="sm:w-auto rounded-sm self-end p-2.5 bg-red-500 hover:bg-red-700 text-white cursor-pointer"
          data-action="click->removal#remove">
            Remove
        </span>
      </div>

      <div data-fields-target="formItemOptions" class="hidden" id="form_item_options_<%= current_id %>">
        <%= render form_item.form_item_options, form_item_id: current_id %>
      </div>

       <%= link_to "Add new option", 
          new_form_item_option_path(form_item_id: current_id), 
          class: blue_btn_classes,
          data: { turbo_stream: true, "fields-target" => "newButton" }
        %>
    </div>
  <% end %>
</div>

app/views/form_items/new.turbo_stream.erb
<%= turbo_stream.append "form_items" do %>
  <%= render @form_item %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Formtya" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Formtya">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/submissions/_items.html.erb
<div class="bg-gray-100 my-5 p-4 rounded-sm">
  
  <%= fields_for "submission[answers_attributes][]", Answer.new do |f| %>
    <%= f.label :value do %>
      <%= f.label "item_#{item.id}", item.label %>
      <%= form_item_field(item, f) %>
    <% end %>
    <%= f.hidden_field :form_item_id, value: item.id %>
  <% end %>
</div>

app/views/submissions/new.html.erb
<%= form_with(model: @submission, class: "contents") do |form| %>
<div class="flex flex-col w-[50%] mx-auto">
  <h1 class="text-4xl mb-4"><%= @foorm.title %></h1>
  
  <%= form.label :submitter, "Your Name" %>
  <%= form.text_field :submitter, placeholder: "Your Name", class: input_classes %>
  <%= form.hidden_field :foorm_id, value: @foorm.id %>

  <%= render partial: "items", collection: @foorm.form_items, as: :item %>

  <div class="inline">
    <%= form.submit "Send", class: blue_btn_classes %>
  </div>
</div>
<% end %>

app/views/submissions/success.html.erb
<h1>Your form has been submitted</h1>
<%= link_to "Inapoi la formulare", foorms_path, class: gray_btn_classes %>